### ISSUE TITLE
Automatically render the human-readable labels for the lexemes and properties

### ISSUE THREAD

**Issue by waldyrious** [lucaswerkmeister/wikidata-lexeme-graph-builder#11]
Perhaps in small, grey text under the input boxes. Not everyone knows the L- and P-codes by heart, so showing them would help assuring them that they're using the right ones :)

**Comment by lucaswerkmeister** [comment]
![Screen Shot 2021-06-12 at 17 54 37](https://user-images.githubusercontent.com/2346599/121781912-473ba400-cba7-11eb-9693-ea3c9fae92ae.png)
