### ISSUE TITLE
Limited to 11 links?

### ISSUE THREAD

**Issue by belett** [lucaswerkmeister/wikidata-lexeme-graph-builder#8]
When I look at https://lucaswerkmeister.github.io/wikidata-lexeme-graph-builder/?subjects=L8160&predicates=P5191 I've got only 11 links from the L8160 but there is more (18 according to https://www.wikidata.org/w/index.php?title=Special%3AWhatLinksHere&target=Lexeme%3AL8160&namespace=146 )

Same if I change the Qid as entrey, z.B. https://lucaswerkmeister.github.io/wikidata-lexeme-graph-builder/?subjects=L8793&predicates=P5191

I guess it's to avoid too big graph but maybe we could have the limit as an input? (maybe also add the iteration as an input, like on https://angryloki.github.io/wikidata-graph-builder/ ;) )

**Comment by lucaswerkmeister** [comment]
Looks like I need to implement support for [continuing queries](https://www.mediawiki.org/wiki/API:Query#Continuing_queries) to get more backlinks.

**Comment by lucaswerkmeister** [comment]
…or I could have just increased the limit from the default 10 to the anonymous maximum of 500, which would probably have been generous enough for almost all cases. (He says, having noticed this just after implementing continuation support…)

**Comment by lucaswerkmeister** [comment]
This looks more complete to me:
![screenshot_2018-08-01 wikidata lexeme graph builder](https://user-images.githubusercontent.com/2346599/43538350-0fda2626-95c2-11e8-971c-f4072d440157.png)
Thanks for the report!

**Comment by belett** [comment]
Yesss, wonderful, thanks!
